### ISSUE TITLE
Separate wrapspawner to other repository

### ISSUE THREAD

**Issue by zonca** [jupyterhub/batchspawner#16]
It is currently very difficult for people to know about WrapSpawner and ProfileSpawner because they are a bit hidden inside this repo.

I know there is a significant request for ProfileSpawner, it is really a very general and useful tool.

What about separating it out to another repository?

**Comment by willingc** [comment]
Seems reasonable to me. @minrk thoughts?

**Comment by minrk** [comment]
Sounds great!

**Comment by willingc** [comment]
@zonca Here's a repo for wrapspawner  https://github.com/jupyterhub/wrapspawner Do you want a separate repo for profilespawner too?

**Comment by zonca** [comment]
I would do one repo for profilespawner that provides also wrapspawner but better see what @mbmilligan thinks first

**Comment by zonca** [comment]
Hmm actually better do the repo for wrapspawner and include profilespawner, profilespawner might be a bit misleading as a name.

**Comment by willingc** [comment]
@mbmilligan I'm still hoping for ``heavymetalspawner`` :wink:

**Comment by mbmilligan** [comment]
No objection here to separating BatchSpawner into its own repo - it only
depends on Jupyterhub itself. I would keep ProfileSpawner with WrapSpawner
though, since the former directly depends on the latter.

Related question - what do folks here think about pulling the RemoteUser
authenticator into the Jupyterhub org?

Michael

**Comment by minrk** [comment]
> what do folks here think about pulling the RemoteUser authenticator into the Jupyterhub org?

Absolutely!

**Comment by zonca** [comment]
gave a first implementation of this,
@mbmilligan, in the `wrapspawner` repo I used an example about `DockerSpawer` which I think is a more common use case. I think the `BatchSpawner` + `ProfilesSpawner` should be in this repo instead.

**Comment by zonca** [comment]
Implemented in https://github.com/jupyterhub/wrapspawner

**Comment by zonca** [comment]
we should remove `wrapspawner` from this repository and add other package as requirement, I'll work on this.

**Comment by zonca** [comment]
ok, see #21

**Comment by mbmilligan** [comment]
Ok, this has been merged and I added a note to the README in both places. Resolving this issue.
