### ISSUE TITLE
Memory leak in batchspawner-singleuser process

### ISSUE THREAD

**Issue by liffiton** [jupyterhub/batchspawner#163]
Twice now, I've seen the `batchspawner-singleuser` process on a node eat up all of the machine's RAM (16GB).  An example entry from `top`:

```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND                                                                                                                                               
12279 [user]    20   0 14.8g  11g 2948 S  0.7 74.8  23:40.61 /share/apps/jhub/bin/python3.6 /share/apps/jhub/bin/batchspawner-singleuser jupyterhub-singleuser --ip=0.0.0.0 --NotebookApp.default_url=/lab
```

I installed Batchspawner using pip via `git+https://github.com/jupyterhub/batchspawner` in August, and pip reports I have version `0.9.0.dev0`.

There are a few dozen users on this system using it regularly, and I've only seen the memory issue twice over the past month.

**Comment by liffiton** [comment]
Hmm, I wasn't clear on Batchspawner's architecture before, but it looks like the `batchspawner-singleuser` process is just running `jupyterhub-singleuser`.  If that's correct, then the issue is likely in the jupyterhub code, right?

**Comment by rkdarst** [comment]
Yes, but that mainly just calls the Jupyter code itself.  So most likely it goes all the way to the jupyter server, which holds different opened stuff in memory (though not the actual kernel variables/state), I woludn't be surprised if making the right notebook could cause memory to continue to increase.

**Comment by liffiton** [comment]
Okay.  Thanks for the info.  Almost certainly an issue somewhere else, then, though it's not clear where exactly.
