### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by iagomez** [jupyterhub/batchspawner#17]
Hey Guys,

First of all thank you for all your work on this project. This is awesome!

I'm extending this project to work with LSF (IBM's workload manager). I'm not familiar with travis-ci so if you guys could give me a hand getting set up or showing me what tool you use to run all the tests locally that would be awesome.

Thanks!

**Comment by iagomez** [comment]
Is it really just activating my repo in travis-ci.org and pushing? Do I need to make any changes to `.travis.yml`?

Thanks!

**Comment by willingc** [comment]
Yes. You should not need to modify the `.travis.yml` on your fork. You may need to go into your fork's repo settings and enable the Travis CI service. After being enabled, it will run Travis on the next push to the fork. Here's a link to the Travis doc basics: https://docs.travis-ci.com/user/for-beginners 

If you wish to run tests locally, you should be able to use [py.test](http://doc.pytest.org/en/latest/) on most jupyter and jupyterhub repos.

**Comment by iagomez** [comment]
Awesome. I was able to trigger a build on travis. Thank you!
