### ISSUE TITLE
Finalize 1.0.0 release

### ISSUE THREAD

**Issue by mbmilligan** [jupyterhub/batchspawner#175]
Need to review release notes, esp for caveats regarding upgrading from earlier versions.

Tagging @rcthomas for testing.

**Comment by rcthomas** [comment]
@mbmilligan I'm dragging a bit here, but will get to this by our next call May 6.

**Comment by rcthomas** [comment]
@mbmilligan I've tested here and this looks good to me.  You can add my positive report to @cmd-ntrf's.

Is this the first release where `batchspawner-singleuser` is in the mix?  I needed to cutomize that setting a little bit but most people probably don't have to.

**Comment by mbmilligan** [comment]
Release done

**Comment by jpellman** [comment]
Any news on when this release might end up in PyPI?  I saw that there was work done a few days ago on setting up a GitHub workflow to automate PyPI deployment [here](https://github.com/jupyterhub/batchspawner/commit/f4ff58719c1d4e6201c3e12e57b2b343ad24a441), but _batchspawner_ still seems to be at version 0.8.1 in [PyPI](https://pypi.org/project/batchspawner/).
