### ISSUE TITLE
`-o pipefail` is a bashism

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/batchspawner#184]
#177 adds `-euo pipefail`, but it seems `-o pipefail` is a bashism.  At least on my Ubuntu it is.  Some of the spawners hardcode the interpreter as `/bin/bash` and some `/bin/sh`.

What do you think is the best way to handle this?  I'd sort of rather not make it interpreter-specific for each of the spawners, since it seems like that will add in another extra thing to think about... but at the same time, is the easiest way to keep things going.

**Comment by mbmilligan** [comment]
Agree this is a bug. Please submit PR removing the problematic `-o pipefail` option. Will cherry-pick to create bugfix release.

**Comment by mbmilligan** [comment]
Correction: PR #177 was not part of the v1.0.0 release, so no need for a buxfix release.
