### ISSUE TITLE
Implement testing

### ISSUE THREAD

**Issue by mbmilligan** [jupyterhub/batchspawner#3]
This project needs testing of some kind.

The best option would be CI with Travis-CI or similar.

Given that this project is inherently interested in communication among multiple nodes in a resource managed system, it has also been suggested to use vagrant or similar to create recipes for test VMs.

However, setting up resource managers is not trivial, and solving that problem for a test environment may consume more time than it's worth. It might be more productive to capture representative outputs from the targeted resources managers and test against scripts that use those outputs to simulate the target environments.

**Comment by zonca** [comment]
thanks @mbmilligan for following up on this, I recommend to begin by evaluating if Travis is feasible at all.
Another option would be to get some permanent VMs from SDSC cloud services. So we could setup them just once, and then connect to them from Travis-CI to do testing of the spawners.

**Comment by mbmilligan** [comment]
@minrk Now that batchspawner has been moved into the org, I'd welcome any thoughts you have about how to take advantage of the testing framework that's already in place for jupyterhub proper.

**Comment by minrk** [comment]
It might be useful to import some of the mocking / fixtures that JupyterHub uses. Other than that, I don't imagine the actual tests over there would be super useful here.

**Comment by mbmilligan** [comment]
Leaving this here for my own planning -- I envision two phases of testing here, and this is probably generalizable to many other Jupyterhub extensions.

1. Unit testing -- monkeypatch out run_command() for an output-capturing substitute and test the various class methods by confirming that the correct command output would be generated. This validates functionality (internal consistency) of the code. This should be straightforward with pytest
2. Integration testing -- import mocking hub and load batchspawner. Use Hub REST API to exercise spawner. Replace command templates with no-op commands and/or instrumentation script calls. This validates interface surface (consistency with Jupyterhub).

**Comment by mbmilligan** [comment]
WIP testing in https://github.com/mbmilligan/batchspawner/tree/add-tests

Running in Travis (https://travis-ci.org/mbmilligan/batchspawner/builds/148061219) suggests a race condition somewhere -- seeing nondeterministic failures associated with the batchspawner.run_command coroutine

@minrk did you run into anything similar when you were setting up testing for jupyterhub?

**Comment by minrk** [comment]
I have seen occasional issues, but generally they were problems with not waiting for async or threading operations that could be fixed in the tests.

**Comment by mbmilligan** [comment]
Strange. Ok, merging the testing work -- at this point the tests **only** fail in Travis, can't reproduce locally -- and with judicious use of retries, the suite as a whole passes in Travis too. Good enough for now. 

@minrk Could you please enable the jupyterhub/batchspawner repo for testing on the jupyterhub Travis-CI account?

**Comment by mbmilligan** [comment]
#13 merged

**Comment by mbmilligan** [comment]
@minrk second ping - can you enable this repo to get tests run under the jupyterhub Travis account?

**Comment by minrk** [comment]
I enabled tests, and I believe you should have permission to do that yourself, now.

**Comment by mbmilligan** [comment]
Note for future reference: with PR #29 the intermittent Travis failures related to subprocesses no longer appear. I suspect this is actually due to some update on the part of Travis, because I don't see how the changes in the PR could have fixed a race condition.

**Comment by willingc** [comment]
Yeah, I suspect you are correct. There are some spurious things we see on Travis.
