### ISSUE TITLE
Define resources/scheduler options using ipywidgets

### ISSUE THREAD

**Issue by willfurnass** [jupyterhub/batchspawner#40]
If resources and scheduler options were defined using / linked to ipywidgets objects then this set of widgets could possibly be used to automate the generation of a `Spawner.options_form`.  

This would allow the user more flexibility when making resource requests than when using an enumerated list of sets of options presented by `wrapspawner.ProfileSpawner`.

However, if the user has the ability to select values per resource independently then there is a possibility that he/she will make an unsatisfiable request.  

Allowing resources to be individually selected using widgets would therefore benefit from being used with a dry-run job validation mechanism (suggested in Issue #36)  

This is something I'd like to work on; suggestions on how best to implement this would be appreciated.

**Comment by mbmilligan** [comment]
Unfortunately this is impossible. `ipywidgets` is a Jupyter notebook feature, but no notebook server is running yet at the time the spawner form is displayed. While we could in principle embed scripts into that page to allow some dynamic interaction, there is no possibility of running server-side code at this stage.
