### ISSUE TITLE
Using Spawner options values for Slurm

### ISSUE THREAD

**Issue by gp4r** [jupyterhub/batchspawner#56]
Hello, I am testing Jypyterhub with Slurm and having a problem to use the values from Spawner option page. I followed Andrea's instruction [https://github.com/jupyterhub/jupyterhub-deploy-hpc/tree/master/batchspawner-xsedeoauth-sshtunnel-sdsccomet](url)
Spawner option page and code seems ok to me, but when I check the log, the actual value in c.SlurmSpawner.batch_script in jupyterhub_config.py doesn't change. Could you help me with this? I appreciate all your help.

comet_spawner.py

from batchspawner import SlurmSpawner
class SpawnerOptions(SlurmSpawner):
  ..............................
 def options_from_form(self, formdata):
    options = {}
    options['queue'] = formdata.get('queue', [''])[0].strip()
    options['runtime'] = formdata.get('runtime', [''])[0].strip()
    return options

jupyterhub_config.py

import os
import sys
from comet_spawner import CometSpawner
c.JupyterHub.spawner_class = CometSpawner
...................................
c.SlurmSpawner.req_queue = 'standard'
c.SlurmSpawner.req_runtime = '12:00:00'
c.SlurmSpawner.batch_script = '''#!/bin/bash
SBATCH --partition={queue}
SBATCH --time={runtime}
....................................

**Comment by zonca** [comment]
try to run jupyterhub interactively with:

    jupyterhub -f jupyterhub_config.py

**Comment by gp4r** [comment]
I have tried it, but got the same result. It used the defined values even though I changed the value through the Spawner options page.

jupyterhub_config.py
`c.SlurmSpawner.req_queue = 'dev-part'
c.SlurmSpawner.req_runtime = '12:00:00'`

I set print in the comet_spawner.py and the options values are
`{'other': '\n#SBATCH --ntasks-per-node=2', 'runtime': '1:00:00', 'queue': 'standard'}`

jupyterhub -f jupyterhub_config.py log
[I 2017-12-20 13:11:58.141 JupyterHub batchspawner:164] Spawner submitted script:
    #!/bin/bash
    #SBATCH --partition=dev-part
    #SBATCH --time=12:00:00

**Comment by zonca** [comment]
please post on gist the complete jupyter_config and comet_spawner

**Comment by gp4r** [comment]
Hello Andrea, I have attached the comet_spawner and jupyter_config
https://gist.github.com/gp4r/4853b478a6f463f9cf97c3e0ce5daf1c
https://gist.github.com/gp4r/a19ff83797b0d1c7ce811ba34681deba
I appreciate you taking the time to help me with this matter.

**Comment by zonca** [comment]
Do you see the form with the options when you login to Jupyterhub?

Il ven 22 dic 2017, 14:54 gp4r <notifications@github.com> ha scritto:

**Comment by gp4r** [comment]
Yes, I can see the options page.
![image](https://user-images.githubusercontent.com/33124907/34302250-2203069c-e6fe-11e7-8542-7a52c790d208.png)

**Comment by zonca** [comment]
And whatever you choose here doesn't change the SLURM script?

Il ven 22 dic 2017, 15:55 gp4r <notifications@github.com> ha scritto:

**Comment by gp4r** [comment]
Yes, that is the problem. Is there a good way to debug this issue?
Thanks again for all your help.

**Comment by zonca** [comment]
you have to set some prints all over, possibly a function is not executed, start from: https://gist.github.com/gp4r/4853b478a6f463f9cf97c3e0ce5daf1c#file-gistfile1-txt-L44

`options_from_form`

also rename the gists to .py so they get syntax highlight

**Comment by zonca** [comment]
try to track the values from the form and try to understand where they get lost

**Comment by gp4r** [comment]
Hello Andrea, I found your different comet_spawner.py code from GitHub which includes `def submit_batch_script(self):` section. After I added the code, it worked perfectly. Thanks for helping me out with this matter, developing the cool stuff, and sharing it. Happy holiday.

**Comment by zonca** [comment]
Good where did you find the one that worked? Happy holidays!

Il ven 22 dic 2017, 20:26 gp4r <notifications@github.com> ha scritto:

**Comment by gp4r** [comment]
I found from https://gist.github.com/zonca/aaed55502c4b16535fe947791d02ac32
Doesn't the comet_spawner.py work with original batchspawner Slurm script? So, you set it inside of comet_spawner.py?

**Comment by zonca** [comment]
I think that what you found initially was for a older version of
batchspawnwer. Can you please make a pull request that to that repository
to add the function that you found in the second file?

Il ven 22 dic 2017, 20:42 gp4r <notifications@github.com> ha scritto:

**Comment by gp4r** [comment]
Looks like you already made a pull request for this issue. https://github.com/jupyterhub/batchspawner/pull/45 However, it hasn't updated yet.

**Comment by mbmilligan** [comment]
#45 has been merged.
