### ISSUE TITLE
SlurmSpawner unable to parse job ID from text

### ISSUE THREAD

**Issue by davidedelvento** [jupyterhub/batchspawner#80]
Looking at the documentation and at the [source code](https://github.com/jupyterhub/batchspawner/blob/master/batchspawner/batchspawner.py#L63), to me it looks like batchspawner expects the output of the submission command being just the job ID. Unfortunately, on the system I am working it is a message such as `Submitted batch job 481417` and therefore it fails with something like: 

`[E 2018-05-15 11:17:50.165 JupyterHub batchspawner:509] SlurmSpawner unable to parse job ID from text: Submitted batch job 481417`

Am I missing something, or should I implement the awk'ing myself?

**Comment by rkdarst** [comment]
Does `sbatch --parsable` also produce this for you?  That's what it uses as can be seen here:
  https://github.com/jupyterhub/batchspawner/blob/master/batchspawner/batchspawner.py#L493
On mine, `--parsable` gives just the job ID, but without that I get what you get.  We run a quite recent slurm, 17.11.

If needed, a regular expression could be added to extract the job ID out of that text, like you see below for some other commands.

**Comment by davidedelvento** [comment]
Thanks @rkdarst : `--parsable` solves the issue, no need to add a regular expression, at least for slurm. The `batch_submit_cmd` example I was following had simply `sbatch` and that misled me.
