### ISSUE TITLE
Support for jupyterhub 0.9 .progress method

### ISSUE THREAD

**Issue by rkdarst** [jupyterhub/batchspawner#81]
batchspawners can be slow, so the JupyterHub 0.9 `.progress` may be useful to us.  This allows real-time progress notifications to the internal state of the spawner:
  https://jupyterhub.readthedocs.io/en/latest/changelog.html#added
(link will eventually break).

I have started working on this in my fork and while maybe it should work, I haven't gotten much useful out of it yet.  I was mainly working on other things, and couldn't get anything useful out...

**Comment by shapovalovts** [comment]
Hey, what is the current status of 0.9 support? Will that commit enough?

**Comment by rkdarst** [comment]
On Thu, Oct 04, 2018 at 09:05:07AM -0700, Taras Shapovalov wrote:
> Hey, what is the current status of 0.9 support? Will that commit enough?

batchspawner already works on 0.9 (and has basically always worked).

The .progress method is an optional feature that can show the progress
as something is spawning.  I couldn't figure out how to do this as
long as we support Python 3.4: it requires *both* coroutines and async
generators.  The only way I have figured out how to do this uses the
"async def" syntax, which is SyntaxError on python 3.4, so source
level incompatibility doesn't work.  I don't know enough about these
two things to do more, and haven't seen a working method from anyone
else.  If someone does know, please tell or make a PR!

Also, many batchspawner instances also use profilespawner.  There is a
profilespawner (in the wrapspawner repo) which needs to be accepted
before it will ever work in profilespawner+batchspawner.

**Comment by psteinb** [comment]
We would be interested to have this feature enabled. I am new to the jupyterhub ecosystem, but am willing to learn. Is there any way I could make this work on a local installation using python3.6?

**Comment by rkdarst** [comment]
I've implemented the basics of this.  Her's the basic idea, this is for discussion about design:

* A `progress` method that polls and checks state (it doesn't hit the batch system while polling, the `start` method does that and updates `self.job_status`).  Just from this, we can emit three different states: "Pending in queue", "Cluster job running... waiting to connect", and "Unknown state" which should never happen.  Already this is pretty useful.
* A method `spawner_progress`, a non-generator coroutine method which can emit spawner-specific state.  `progress` also polls this, if there is anything there it adds it to its messages.
  * For SlurmSpawner, I've made something that prints the estimated start time (which slurm nicely provides).  Under normal circumstances it never shows because stuff starts too fast, but could be useful.  It will be useful to say if start time is too long in the future (in my case, there's an upcoming reservation and no batch jobs can schedule - current handling of this is not very user friendly).  Estimated start time is returned by the `estimated_starttime` coroutine, and some basic formatting of this is in `progress`.
* `progress` makes a list of all of the relevant messages and yields them if they are different from the previous set of messages.

What do you think?  Do you have any other ideas for how we should use this?

The PR #86, but my newer stuff is not public yet.  Doing anything is hard until some more stuff gets integrated, and this is more of an adventurous change.
